# Generated by Django 5.2.7 on 2025-11-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Access_Resource',
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20)),
                ('read_own', models.BooleanField(default=False)),
                ('read_all', models.BooleanField(default=False)),
                ('create', models.BooleanField(default=False)),
                ('update_own', models.BooleanField(default=False)),
                ('update_all', models.BooleanField(default=False)),
                ('delete_own', models.BooleanField(default=False)),
                ('delete_all', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accesses.resource')),
            ],
            options={
                'verbose_name': 'Access Rule',
                'verbose_name_plural': 'Access Rules',
                'db_table': 'Access_Rule',
                'unique_together': {('role', 'resource')},
            },
        ),
    ]
