# Generated by Django 5.2.7 on 2025-11-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklistedtoken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Blacklisted Token', 'verbose_name_plural': 'Blacklisted Tokens'},
        ),
        migrations.AlterModelTable(
            name='blacklistedtoken',
            table='BlacklistedTokens',
        ),
    ]
