# Generated by Django 5.2.7 on 2025-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_deleted_userprofile_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_phone_number_when_set',
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token_type',
            field=models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), fields=('phone_number',), name='unique_phone_number_when_set'),
        ),
    ]
